/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SchoolBracketRouteImport } from './routes/school-bracket'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForTeachersRouteImport } from './routes/for-teachers'
import { Route as EnterResultRouteImport } from './routes/enter-result'
import { Route as BracketRouteImport } from './routes/bracket'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BracketSchoolRouteImport } from './routes/bracket.$school'
import { Route as ApiMatch_resultsRouteImport } from './routes/api/match_results'
import { Route as AdminSignupsRouteImport } from './routes/admin.signups'
import { Route as AdminScoresRouteImport } from './routes/admin.scores'
import { Route as AdminRosterRouteImport } from './routes/admin.roster'
import { Route as AdminReportRouteImport } from './routes/admin.report'
import { Route as ApiSurveyStudentRouteImport } from './routes/api/survey.student'
import { Route as ApiSurveyStaffRouteImport } from './routes/api/survey.staff'
import { Route as ApiPlayoffUpdateStatusRouteImport } from './routes/api/playoff.update-status'
import { Route as ApiPlayoffSignupsRouteImport } from './routes/api/playoff.signups'
import { Route as ApiPlayoffSignupRouteImport } from './routes/api/playoff.signup'
import { Route as ApiPlayoffSchoolSettingsRouteImport } from './routes/api/playoff.school-settings'
import { Route as ApiPlayoffPublishBracketRouteImport } from './routes/api/playoff.publish-bracket'
import { Route as ApiPlayoffPublicBracketRouteImport } from './routes/api/playoff.public-bracket'
import { Route as ApiPlayoffGenerateRoundRobinRouteImport } from './routes/api/playoff.generate-round-robin'
import { Route as ApiPlayoffCountRouteImport } from './routes/api/playoff.count'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolBracketRoute = SchoolBracketRouteImport.update({
  id: '/school-bracket',
  path: '/school-bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersRoute = ForTeachersRouteImport.update({
  id: '/for-teachers',
  path: '/for-teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterResultRoute = EnterResultRouteImport.update({
  id: '/enter-result',
  path: '/enter-result',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketRoute = BracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketSchoolRoute = BracketSchoolRouteImport.update({
  id: '/$school',
  path: '/$school',
  getParentRoute: () => BracketRoute,
} as any)
const ApiMatch_resultsRoute = ApiMatch_resultsRouteImport.update({
  id: '/api/match_results',
  path: '/api/match_results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupsRoute = AdminSignupsRouteImport.update({
  id: '/signups',
  path: '/signups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRosterRoute = AdminRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSurveyStudentRoute = ApiSurveyStudentRouteImport.update({
  id: '/api/survey/student',
  path: '/api/survey/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveyStaffRoute = ApiSurveyStaffRouteImport.update({
  id: '/api/survey/staff',
  path: '/api/survey/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffUpdateStatusRoute = ApiPlayoffUpdateStatusRouteImport.update({
  id: '/api/playoff/update-status',
  path: '/api/playoff/update-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffSignupsRoute = ApiPlayoffSignupsRouteImport.update({
  id: '/api/playoff/signups',
  path: '/api/playoff/signups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffSignupRoute = ApiPlayoffSignupRouteImport.update({
  id: '/api/playoff/signup',
  path: '/api/playoff/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffSchoolSettingsRoute =
  ApiPlayoffSchoolSettingsRouteImport.update({
    id: '/api/playoff/school-settings',
    path: '/api/playoff/school-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayoffPublishBracketRoute =
  ApiPlayoffPublishBracketRouteImport.update({
    id: '/api/playoff/publish-bracket',
    path: '/api/playoff/publish-bracket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayoffPublicBracketRoute = ApiPlayoffPublicBracketRouteImport.update({
  id: '/api/playoff/public-bracket',
  path: '/api/playoff/public-bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayoffGenerateRoundRobinRoute =
  ApiPlayoffGenerateRoundRobinRouteImport.update({
    id: '/api/playoff/generate-round-robin',
    path: '/api/playoff/generate-round-robin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayoffCountRoute = ApiPlayoffCountRouteImport.update({
  id: '/api/playoff/count',
  path: '/api/playoff/count',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bracket': typeof BracketRouteWithChildren
  '/enter-result': typeof EnterResultRoute
  '/for-teachers': typeof ForTeachersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/school-bracket': typeof SchoolBracketRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/tournament': typeof TournamentRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/api/match_results': typeof ApiMatch_resultsRoute
  '/bracket/$school': typeof BracketSchoolRoute
  '/api/playoff/count': typeof ApiPlayoffCountRoute
  '/api/playoff/generate-round-robin': typeof ApiPlayoffGenerateRoundRobinRoute
  '/api/playoff/public-bracket': typeof ApiPlayoffPublicBracketRoute
  '/api/playoff/publish-bracket': typeof ApiPlayoffPublishBracketRoute
  '/api/playoff/school-settings': typeof ApiPlayoffSchoolSettingsRoute
  '/api/playoff/signup': typeof ApiPlayoffSignupRoute
  '/api/playoff/signups': typeof ApiPlayoffSignupsRoute
  '/api/playoff/update-status': typeof ApiPlayoffUpdateStatusRoute
  '/api/survey/staff': typeof ApiSurveyStaffRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bracket': typeof BracketRouteWithChildren
  '/enter-result': typeof EnterResultRoute
  '/for-teachers': typeof ForTeachersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/school-bracket': typeof SchoolBracketRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/tournament': typeof TournamentRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/api/match_results': typeof ApiMatch_resultsRoute
  '/bracket/$school': typeof BracketSchoolRoute
  '/api/playoff/count': typeof ApiPlayoffCountRoute
  '/api/playoff/generate-round-robin': typeof ApiPlayoffGenerateRoundRobinRoute
  '/api/playoff/public-bracket': typeof ApiPlayoffPublicBracketRoute
  '/api/playoff/publish-bracket': typeof ApiPlayoffPublishBracketRoute
  '/api/playoff/school-settings': typeof ApiPlayoffSchoolSettingsRoute
  '/api/playoff/signup': typeof ApiPlayoffSignupRoute
  '/api/playoff/signups': typeof ApiPlayoffSignupsRoute
  '/api/playoff/update-status': typeof ApiPlayoffUpdateStatusRoute
  '/api/survey/staff': typeof ApiSurveyStaffRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bracket': typeof BracketRouteWithChildren
  '/enter-result': typeof EnterResultRoute
  '/for-teachers': typeof ForTeachersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/school-bracket': typeof SchoolBracketRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/tournament': typeof TournamentRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/signups': typeof AdminSignupsRoute
  '/api/match_results': typeof ApiMatch_resultsRoute
  '/bracket/$school': typeof BracketSchoolRoute
  '/api/playoff/count': typeof ApiPlayoffCountRoute
  '/api/playoff/generate-round-robin': typeof ApiPlayoffGenerateRoundRobinRoute
  '/api/playoff/public-bracket': typeof ApiPlayoffPublicBracketRoute
  '/api/playoff/publish-bracket': typeof ApiPlayoffPublishBracketRoute
  '/api/playoff/school-settings': typeof ApiPlayoffSchoolSettingsRoute
  '/api/playoff/signup': typeof ApiPlayoffSignupRoute
  '/api/playoff/signups': typeof ApiPlayoffSignupsRoute
  '/api/playoff/update-status': typeof ApiPlayoffUpdateStatusRoute
  '/api/survey/staff': typeof ApiSurveyStaffRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bracket'
    | '/enter-result'
    | '/for-teachers'
    | '/leaderboard'
    | '/school-bracket'
    | '/sign-up'
    | '/signup'
    | '/standings'
    | '/tournament'
    | '/admin/report'
    | '/admin/roster'
    | '/admin/scores'
    | '/admin/signups'
    | '/api/match_results'
    | '/bracket/$school'
    | '/api/playoff/count'
    | '/api/playoff/generate-round-robin'
    | '/api/playoff/public-bracket'
    | '/api/playoff/publish-bracket'
    | '/api/playoff/school-settings'
    | '/api/playoff/signup'
    | '/api/playoff/signups'
    | '/api/playoff/update-status'
    | '/api/survey/staff'
    | '/api/survey/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bracket'
    | '/enter-result'
    | '/for-teachers'
    | '/leaderboard'
    | '/school-bracket'
    | '/sign-up'
    | '/signup'
    | '/standings'
    | '/tournament'
    | '/admin/report'
    | '/admin/roster'
    | '/admin/scores'
    | '/admin/signups'
    | '/api/match_results'
    | '/bracket/$school'
    | '/api/playoff/count'
    | '/api/playoff/generate-round-robin'
    | '/api/playoff/public-bracket'
    | '/api/playoff/publish-bracket'
    | '/api/playoff/school-settings'
    | '/api/playoff/signup'
    | '/api/playoff/signups'
    | '/api/playoff/update-status'
    | '/api/survey/staff'
    | '/api/survey/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bracket'
    | '/enter-result'
    | '/for-teachers'
    | '/leaderboard'
    | '/school-bracket'
    | '/sign-up'
    | '/signup'
    | '/standings'
    | '/tournament'
    | '/admin/report'
    | '/admin/roster'
    | '/admin/scores'
    | '/admin/signups'
    | '/api/match_results'
    | '/bracket/$school'
    | '/api/playoff/count'
    | '/api/playoff/generate-round-robin'
    | '/api/playoff/public-bracket'
    | '/api/playoff/publish-bracket'
    | '/api/playoff/school-settings'
    | '/api/playoff/signup'
    | '/api/playoff/signups'
    | '/api/playoff/update-status'
    | '/api/survey/staff'
    | '/api/survey/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BracketRoute: typeof BracketRouteWithChildren
  EnterResultRoute: typeof EnterResultRoute
  ForTeachersRoute: typeof ForTeachersRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SchoolBracketRoute: typeof SchoolBracketRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  StandingsRoute: typeof StandingsRoute
  TournamentRoute: typeof TournamentRoute
  ApiMatch_resultsRoute: typeof ApiMatch_resultsRoute
  ApiPlayoffCountRoute: typeof ApiPlayoffCountRoute
  ApiPlayoffGenerateRoundRobinRoute: typeof ApiPlayoffGenerateRoundRobinRoute
  ApiPlayoffPublicBracketRoute: typeof ApiPlayoffPublicBracketRoute
  ApiPlayoffPublishBracketRoute: typeof ApiPlayoffPublishBracketRoute
  ApiPlayoffSchoolSettingsRoute: typeof ApiPlayoffSchoolSettingsRoute
  ApiPlayoffSignupRoute: typeof ApiPlayoffSignupRoute
  ApiPlayoffSignupsRoute: typeof ApiPlayoffSignupsRoute
  ApiPlayoffUpdateStatusRoute: typeof ApiPlayoffUpdateStatusRoute
  ApiSurveyStaffRoute: typeof ApiSurveyStaffRoute
  ApiSurveyStudentRoute: typeof ApiSurveyStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-bracket': {
      id: '/school-bracket'
      path: '/school-bracket'
      fullPath: '/school-bracket'
      preLoaderRoute: typeof SchoolBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers': {
      id: '/for-teachers'
      path: '/for-teachers'
      fullPath: '/for-teachers'
      preLoaderRoute: typeof ForTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter-result': {
      id: '/enter-result'
      path: '/enter-result'
      fullPath: '/enter-result'
      preLoaderRoute: typeof EnterResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket': {
      id: '/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof BracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket/$school': {
      id: '/bracket/$school'
      path: '/$school'
      fullPath: '/bracket/$school'
      preLoaderRoute: typeof BracketSchoolRouteImport
      parentRoute: typeof BracketRoute
    }
    '/api/match_results': {
      id: '/api/match_results'
      path: '/api/match_results'
      fullPath: '/api/match_results'
      preLoaderRoute: typeof ApiMatch_resultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signups': {
      id: '/admin/signups'
      path: '/signups'
      fullPath: '/admin/signups'
      preLoaderRoute: typeof AdminSignupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scores': {
      id: '/admin/scores'
      path: '/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminScoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roster': {
      id: '/admin/roster'
      path: '/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AdminRosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/survey/student': {
      id: '/api/survey/student'
      path: '/api/survey/student'
      fullPath: '/api/survey/student'
      preLoaderRoute: typeof ApiSurveyStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey/staff': {
      id: '/api/survey/staff'
      path: '/api/survey/staff'
      fullPath: '/api/survey/staff'
      preLoaderRoute: typeof ApiSurveyStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/update-status': {
      id: '/api/playoff/update-status'
      path: '/api/playoff/update-status'
      fullPath: '/api/playoff/update-status'
      preLoaderRoute: typeof ApiPlayoffUpdateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/signups': {
      id: '/api/playoff/signups'
      path: '/api/playoff/signups'
      fullPath: '/api/playoff/signups'
      preLoaderRoute: typeof ApiPlayoffSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/signup': {
      id: '/api/playoff/signup'
      path: '/api/playoff/signup'
      fullPath: '/api/playoff/signup'
      preLoaderRoute: typeof ApiPlayoffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/school-settings': {
      id: '/api/playoff/school-settings'
      path: '/api/playoff/school-settings'
      fullPath: '/api/playoff/school-settings'
      preLoaderRoute: typeof ApiPlayoffSchoolSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/publish-bracket': {
      id: '/api/playoff/publish-bracket'
      path: '/api/playoff/publish-bracket'
      fullPath: '/api/playoff/publish-bracket'
      preLoaderRoute: typeof ApiPlayoffPublishBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/public-bracket': {
      id: '/api/playoff/public-bracket'
      path: '/api/playoff/public-bracket'
      fullPath: '/api/playoff/public-bracket'
      preLoaderRoute: typeof ApiPlayoffPublicBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/generate-round-robin': {
      id: '/api/playoff/generate-round-robin'
      path: '/api/playoff/generate-round-robin'
      fullPath: '/api/playoff/generate-round-robin'
      preLoaderRoute: typeof ApiPlayoffGenerateRoundRobinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playoff/count': {
      id: '/api/playoff/count'
      path: '/api/playoff/count'
      fullPath: '/api/playoff/count'
      preLoaderRoute: typeof ApiPlayoffCountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminReportRoute: typeof AdminReportRoute
  AdminRosterRoute: typeof AdminRosterRoute
  AdminScoresRoute: typeof AdminScoresRoute
  AdminSignupsRoute: typeof AdminSignupsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportRoute: AdminReportRoute,
  AdminRosterRoute: AdminRosterRoute,
  AdminScoresRoute: AdminScoresRoute,
  AdminSignupsRoute: AdminSignupsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BracketRouteChildren {
  BracketSchoolRoute: typeof BracketSchoolRoute
}

const BracketRouteChildren: BracketRouteChildren = {
  BracketSchoolRoute: BracketSchoolRoute,
}

const BracketRouteWithChildren =
  BracketRoute._addFileChildren(BracketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BracketRoute: BracketRouteWithChildren,
  EnterResultRoute: EnterResultRoute,
  ForTeachersRoute: ForTeachersRoute,
  LeaderboardRoute: LeaderboardRoute,
  SchoolBracketRoute: SchoolBracketRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  StandingsRoute: StandingsRoute,
  TournamentRoute: TournamentRoute,
  ApiMatch_resultsRoute: ApiMatch_resultsRoute,
  ApiPlayoffCountRoute: ApiPlayoffCountRoute,
  ApiPlayoffGenerateRoundRobinRoute: ApiPlayoffGenerateRoundRobinRoute,
  ApiPlayoffPublicBracketRoute: ApiPlayoffPublicBracketRoute,
  ApiPlayoffPublishBracketRoute: ApiPlayoffPublishBracketRoute,
  ApiPlayoffSchoolSettingsRoute: ApiPlayoffSchoolSettingsRoute,
  ApiPlayoffSignupRoute: ApiPlayoffSignupRoute,
  ApiPlayoffSignupsRoute: ApiPlayoffSignupsRoute,
  ApiPlayoffUpdateStatusRoute: ApiPlayoffUpdateStatusRoute,
  ApiSurveyStaffRoute: ApiSurveyStaffRoute,
  ApiSurveyStudentRoute: ApiSurveyStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
