/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSurveyStudentRouteImport } from './routes/api/survey.student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveyStudentRoute = ApiSurveyStudentRouteImport.update({
  id: '/api/survey/student',
  path: '/api/survey/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/survey/student': typeof ApiSurveyStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/survey/student'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/survey/student'
  id: '__root__' | '/' | '/api/survey/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSurveyStudentRoute: typeof ApiSurveyStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey/student': {
      id: '/api/survey/student'
      path: '/api/survey/student'
      fullPath: '/api/survey/student'
      preLoaderRoute: typeof ApiSurveyStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSurveyStudentRoute: ApiSurveyStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
